from . import domestic_money_transfer
from . import domestic_money_transfer_categories
from . import multiple_location_transfer
from . import multiple_location_transfer_categories
from . import domestic_money_transfer_id
from . import domestic_money_transfer_id_categories
from . import customer_pay
from . import customer_pay_categories
from . import revenue_service
from . import revenue_service_categories
from . import revenue_check_service
from . import revenue_check_service_categories
from . import reference_question
from . import reference_question_categories
